[package]
name = "meshopt-codec-parity"
version = "0.0.0"
edition = "2021"
rust-version = "1.88"
publish = false

[dependencies]
meshoptimizer-rs = { path = "../..", default-features = false }

[lib]
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "codec-driver"
path = "main.rs"

[profile.release]
codegen-units = 1
lto = "fat"
