#include "meshoptimizer.h"
#define CLUSTERLOD_IMPLEMENTATION
// Release demo assertions contain a width-32 shift that has no defined value.
// Library/fixture assertions remain enabled in their separate translation units.
#define NDEBUG
#include <assert.h>
#include "clusterlod.h"
#undef NDEBUG
#include <assert.h>
#include <vector>
#include <cstdio>
#include <cstring>
#include <stdexcept>
#include <chrono>
#include <cfenv>
#include <cmath>
#include <cstdint>
#include <algorithm>
using Bytes=std::vector<unsigned char>;
unsigned word(const Bytes&b,size_t i){if(i+4>b.size())throw std::runtime_error("short");return unsigned(b[i])|unsigned(b[i+1])<<8|unsigned(b[i+2])<<16|unsigned(b[i+3])<<24;}
float fl(unsigned v){float f;memcpy(&f,&v,4);return f;}
void push(Bytes&o,unsigned v){for(int k=0;k<4;k++)o.push_back(v>>(k*8));}
void lod_bounds(Bytes&o,clodBounds b){for(float f:{b.center[0],b.center[1],b.center[2],b.radius,b.error}){unsigned v;memcpy(&v,&f,4);push(o,v);}}
void bounds(Bytes&o,meshopt_Bounds b){for(int i=0;i<3;i++){unsigned v;memcpy(&v,&b.center[i],4);push(o,v);}unsigned v;memcpy(&v,&b.radius,4);push(o,v);for(float *p:{b.cone_apex,b.cone_axis})for(int i=0;i<3;i++){memcpy(&v,&p[i],4);push(o,v);}memcpy(&v,&b.cone_cutoff,4);push(o,v);for(int i=0;i<3;i++)o.push_back(b.cone_axis_s8[i]);o.push_back(b.cone_cutoff_s8);}
static std::vector<std::pair<void*,size_t>> tracked;
static size_t current=0,peak=0,output_bytes=0;
static bool measuring=false;
void* tracked_new(size_t n){void*p=::operator new(n);tracked.push_back({p,n});current+=n;peak=std::max(peak,current+output_bytes);return p;}
void tracked_delete(void*p){auto it=std::find_if(tracked.begin(),tracked.end(),[&](auto v){return v.first==p;});if(it==tracked.end())std::abort();current-=it->second;tracked.erase(it);::operator delete(p);}
void requested_output(size_t n){output_bytes=n;peak=std::max(peak,current+n);}
Bytes execute(const Bytes&b){if(b.size()<48||memcmp(b.data(),"MO03",4))throw std::runtime_error("version");bool timing_only=word(b,4)&0x20000;bool into=word(b,4)&0x10000;unsigned op=word(b,4)&0xffff,nv=word(b,8),ni=word(b,12),mv=word(b,16),min=word(b,20),mt=word(b,24),target=word(b,36),nc=word(b,40),repeats=word(b,44);float weight=fl(word(b,28)),split=fl(word(b,32));if(b.size()!=48+size_t(nv)*16+size_t(ni)*4+size_t(nc)*4)throw std::runtime_error("length");std::vector<float>p(nv*3),r(nv);std::vector<unsigned>idx(ni),counts(nc);size_t at=48;for(float&v:p){v=fl(word(b,at));at+=4;}for(unsigned&v:idx){v=word(b,at);at+=4;}for(unsigned&v:counts){v=word(b,at);at+=4;}for(float&v:r){v=fl(word(b,at));at+=4;}
if(op==16){clodConfig c=(target&1)?clodDefaultConfigRT(mt):clodDefaultConfig(mt);c.partition_size=mv;c.partition_sort=target&2;c.simplify_regularize=target&4;c.simplify_preserve_folds=target&8;c.simplify_dilate_borders=target&16;c.simplify_error_edge_limit=(target&32)?1.5f:0.f;c.optimize_bounds=target&64;c.simplify_permissive=!(target&128);c.simplify_fallback_permissive=target&128;c.simplify_fallback_sloppy=!(target&256);if(target&4096){c.optimize_clusters_level=(target>>13)%10;c.simplify_ratio=0.25f;}
size_t width=nc?((target>>20)&31)+1:0;std::vector<float>attributes,widths;std::vector<unsigned char>locks(nv);if(width==1)attributes=r;else if(width>0){if(counts.size()!=nv*width)throw std::runtime_error("attribute length");for(unsigned v:counts)attributes.push_back(fl(v));}for(size_t k=0;k<width;k++)widths.push_back(split*float(k+1));for(size_t i=0;i<nv;i++)locks[i]=(target&1024)?i%8:0;
clodMesh mesh={};mesh.indices=idx.data();mesh.index_count=ni;mesh.vertex_count=nv;mesh.vertex_positions=p.data();mesh.vertex_positions_stride=12;mesh.vertex_attributes=width?attributes.data():nullptr;mesh.vertex_attributes_stride=width*4;mesh.attribute_weights=widths.data();mesh.attribute_count=width;mesh.vertex_lock=(target&1024)?locks.data():nullptr;mesh.attribute_protect_mask=(target&512)?1:0;Bytes data;std::vector<clodGroup>groups;clodBuild(c,mesh,[&](clodGroup g,const clodCluster*cl,size_t n){int id=(target&2048)?groups.size()*7+2:groups.size();groups.push_back(g);push(data,g.depth);lod_bounds(data,g.simplified);push(data,n);for(size_t i=0;i<n;i++){push(data,cl[i].refined);lod_bounds(data,cl[i].bounds);push(data,cl[i].vertex_count);push(data,cl[i].index_count);for(size_t j=0;j<cl[i].index_count;j++)push(data,cl[i].indices[j]);}return id;});Bytes o;push(o,groups.size());o.insert(o.end(),data.begin(),data.end());for(float f:p){unsigned v;memcpy(&v,&f,4);push(o,v);}size_t levels=0;for(auto g:groups)levels=std::max(levels,size_t(g.depth+1));size_t bound=clodBuildHierarchyBound(groups.size(),min,levels);std::vector<clodNode>nodes(bound);size_t n=clodBuildHierarchy(nodes.data(),groups.data(),groups.size(),min,levels);push(o,bound);push(o,n);for(size_t i=0;i<n;i++){lod_bounds(o,nodes[i].bounds);push(o,nodes[i].group);push(o,nodes[i].child_offset);push(o,nodes[i].child_count);}Bytes out{'M','R','0','3'};push(out,o.size());out.insert(out.end(),o.begin(),o.end());out.insert(out.end(),16,0);return out;}
std::vector<unsigned>lv(256);std::vector<unsigned char>lt(ni);size_t ln=0;if(op==7||op==9||op==10)ln=meshopt_extractMeshletIndices(lv.data(),lt.data(),idx.data(),ni);
std::vector<meshopt_Meshlet> out_m(into&&op<=4?meshopt_buildMeshletsBound(ni,mv,op<=2?mt:min):0);
std::vector<unsigned>out_v(into?(op<=4||op==14?ni:op>=9&&op<=11?256:op==12?nc:nv):0);
std::vector<unsigned char>out_t(into&&(op<=4||op>=9&&op<=11)?ni:0);
auto run=[&](bool collect){Bytes o;
if(op==1||op==3||op==4||op==6||op==7||op==8||op>=12){if(!(op==12&&(target&0x80000000)))for(float f:p)if(!std::isfinite(f))throw std::runtime_error("nonfinite");}
if(op<=4||op==6||op==7||op==12||op==14){if(op!=12&&ni%3)throw std::runtime_error("topology");for(unsigned v:idx)if(v>=nv)throw std::runtime_error("index");}
if(op<=4){size_t bound=meshopt_buildMeshletsBound(ni,mv,op<=2?mt:min);std::vector<meshopt_Meshlet>alloc_m(into?0:bound);std::vector<unsigned>alloc_v(into?0:ni);std::vector<unsigned char>alloc_t(into?0:ni);auto&m=into?out_m:alloc_m;auto&v=into?out_v:alloc_v;auto&t=into?out_t:alloc_t;if(measuring)requested_output(into?0:m.capacity()*sizeof(meshopt_Meshlet)+v.capacity()*4+t.capacity());size_t n=op==1?meshopt_buildMeshlets(m.data(),v.data(),t.data(),idx.data(),ni,p.data(),nv,12,mv,mt,weight):op==2?meshopt_buildMeshletsScan(m.data(),v.data(),t.data(),idx.data(),ni,nv,mv,mt):op==3?meshopt_buildMeshletsFlex(m.data(),v.data(),t.data(),idx.data(),ni,p.data(),nv,12,mv,min,mt,weight,split):meshopt_buildMeshletsSpatial(m.data(),v.data(),t.data(),idx.data(),ni,p.data(),nv,12,mv,min,mt,weight);if(!collect)return o;size_t vc=n?m[n-1].vertex_offset+m[n-1].vertex_count:0,tc=n?m[n-1].triangle_offset+m[n-1].triangle_count*3:0;push(o,n);push(o,vc);push(o,tc);for(size_t i=0;i<n;i++){push(o,m[i].vertex_offset);push(o,m[i].triangle_offset);push(o,m[i].vertex_count);push(o,m[i].triangle_count);}for(size_t i=0;i<vc;i++)push(o,v[i]);o.insert(o.end(),t.begin(),t.begin()+tc);}
else if(op==5){size_t n=meshopt_buildMeshletsBound(ni,mv,mt);if(collect)push(o,n);}else if(op==6){auto bounds_=meshopt_computeClusterBounds(idx.data(),ni,p.data(),nv,12);if(collect)bounds(o,bounds_);}else if(op==7){auto bounds_=meshopt_computeMeshletBounds(lv.data(),lt.data(),ni/3,p.data(),nv,12);if(collect)bounds(o,bounds_);}else if(op==8){if(target)for(float f:r)if(!std::isfinite(f)||f<0)throw std::runtime_error("radius");auto bounds_=meshopt_computeSphereBounds(p.data(),nv,12,target?r.data():nullptr,4);if(collect)bounds(o,bounds_);}else if(op>=9&&op<=11){std::vector<unsigned>alloc_v;std::vector<unsigned char>alloc_t;
if(!into){if(op==11){unsigned tv[256];unsigned char tt[1536];size_t count=meshopt_extractMeshletIndices(tv,tt,idx.data(),ni);alloc_v.assign(tv,tv+count);alloc_t.assign(tt,tt+ni);}else{alloc_v.assign(lv.begin(),lv.begin()+ln);alloc_t=lt;}}
auto&v=into?out_v:alloc_v;auto&t=into?out_t:alloc_t;size_t n=ln;
if(measuring)requested_output(into?0:v.capacity()*4+t.capacity());
if(op==11){if(into)n=meshopt_extractMeshletIndices(v.data(),t.data(),idx.data(),ni);else n=v.size();}else{if(into){std::copy(lv.begin(),lv.begin()+ln,v.begin());std::copy(lt.begin(),lt.end(),t.begin());}if(op==9)meshopt_optimizeMeshlet(v.data(),t.data(),ni/3,n);else meshopt_optimizeMeshletLevel(v.data(),n,t.data(),ni/3,target);}if(!collect)return o;push(o,n);for(size_t i=0;i<n;i++)push(o,v[i]);o.insert(o.end(),t.begin(),t.end());}else if(op==12){std::vector<unsigned>alloc_d(into?0:nc);auto&d=into?out_v:alloc_d;if(measuring)requested_output(into?0:d.capacity()*4);size_t n=meshopt_partitionClusters(d.data(),idx.data(),ni,counts.data(),nc,(target&0x80000000)?nullptr:p.data(),nv,12,target&0x7fffffff);if(!collect)return o;push(o,n);for(unsigned v:d)push(o,v);}else{std::vector<unsigned>alloc_d(into?0:op==14?ni:nv);auto&d=into?out_v:alloc_d;if(measuring)requested_output(into?0:d.capacity()*4);if(op==13)meshopt_spatialSortRemap(d.data(),p.data(),nv,12);else if(op==14)meshopt_spatialSortTriangles(d.data(),idx.data(),ni,p.data(),nv,12);else if(op==15)meshopt_spatialClusterPoints(d.data(),p.data(),nv,12,target);else throw std::runtime_error("op");if(!collect)return o;for(unsigned v:d)push(o,v);}return o;};tracked.clear();tracked.reserve(128);current=peak=output_bytes=0;meshopt_setAllocator(tracked_new,tracked_delete);measuring=true;Bytes result=run(!timing_only);size_t storage=peak;measuring=false;if(current!=0)std::abort();meshopt_setAllocator(::operator new,::operator delete);auto start=std::chrono::steady_clock::now();
// D78: the bound is ~20 ns of arithmetic, so both drivers time the bare call
// (inputs and result opaque to the optimizer) instead of the dispatch lambda.
if(op==5){size_t a=ni,b=mv,c=mt;for(unsigned i=0;i<repeats;i++){asm volatile("":"+r"(a),"+r"(b),"+r"(c));size_t r=meshopt_buildMeshletsBound(a,b,c);asm volatile(""::"r"(r));}}else for(unsigned i=0;i<repeats;i++)run(false);double elapsed=repeats?std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count()/repeats:0.;Bytes out{'M','R','0','3'};push(out,result.size());out.insert(out.end(),result.begin(),result.end());const auto*e=reinterpret_cast<const unsigned char*>(&elapsed);out.insert(out.end(),e,e+8);const auto*mem=reinterpret_cast<const unsigned char*>(&storage);out.insert(out.end(),mem,mem+8);return out;}
int main(){if(fegetround()!=FE_TONEAREST||std::numeric_limits<float>::denorm_min()*2==0)return 2;for(;;){unsigned char hdr[4];if(fread(hdr,1,4,stdin)!=4)break;Bytes h(hdr,hdr+4);unsigned n=word(h,0);if(n>128*1024*1024)return 3;Bytes b(n);if(fread(b.data(),1,n,stdin)!=n)return 4;Bytes o=execute(b);Bytes len;push(len,o.size());fwrite(len.data(),1,4,stdout);fwrite(o.data(),1,o.size(),stdout);fflush(stdout);}return 0;}
