[package]
name="meshopt-codec-fuzz"
version="0.0.0"
edition="2021"
publish=false
[package.metadata]
cargo-fuzz=true
[dependencies]
libfuzzer-sys="=0.4.13"
meshoptimizer-rs={path="../..",default-features=false,features=["std","simd","parity-internals"]}
[lib]
path="src.rs"
[workspace]
members=["."]

[[bin]]
name="vertex"
path="fuzz_targets/vertex.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_into"
path="fuzz_targets/vertex_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="triangles"
path="fuzz_targets/triangles.rs"
test=false
doc=false
bench=false

[[bin]]
name="triangles_into"
path="fuzz_targets/triangles_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence"
path="fuzz_targets/sequence.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence_into"
path="fuzz_targets/sequence_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="oct"
path="fuzz_targets/oct.rs"
test=false
doc=false
bench=false

[[bin]]
name="quat"
path="fuzz_targets/quat.rs"
test=false
doc=false
bench=false

[[bin]]
name="exp"
path="fuzz_targets/exp.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_version"
path="fuzz_targets/vertex_version.rs"
test=false
doc=false
bench=false

[[bin]]
name="index_version"
path="fuzz_targets/index_version.rs"
test=false
doc=false
bench=false

[[bin]]
name="view"
path="fuzz_targets/view.rs"
test=false
doc=false
bench=false

[[bin]]
name="view_into"
path="fuzz_targets/view_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_encode"
path="fuzz_targets/vertex_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_encode_into"
path="fuzz_targets/vertex_encode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="index_encode"
path="fuzz_targets/index_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="index_encode_into"
path="fuzz_targets/index_encode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence_encode"
path="fuzz_targets/sequence_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence_encode_into"
path="fuzz_targets/sequence_encode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="oct_encode"
path="fuzz_targets/oct_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="quat_encode"
path="fuzz_targets/quat_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="exp_encode"
path="fuzz_targets/exp_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="color_encode"
path="fuzz_targets/color_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="color"
path="fuzz_targets/color.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_encode"
path="fuzz_targets/meshlet_encode.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_encode_into"
path="fuzz_targets/meshlet_encode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_decode"
path="fuzz_targets/meshlet_decode.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_decode_into"
path="fuzz_targets/meshlet_decode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_raw"
path="fuzz_targets/meshlet_raw.rs"
test=false
doc=false
bench=false

[[bin]]
name="meshlet_raw_into"
path="fuzz_targets/meshlet_raw_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="bounds"
path="fuzz_targets/bounds.rs"
test=false
doc=false
bench=false

[[bin]]
name="filter_encode_into"
path="fuzz_targets/filter_encode_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="simd"
path="fuzz_targets/simd.rs"
test=false
doc=false
bench=false
