[package]
name="meshopt-codec-fuzz"
version="0.0.0"
edition="2021"
publish=false
[package.metadata]
cargo-fuzz=true
[dependencies]
libfuzzer-sys="=0.4.13"
meshoptimizer-rs={path="../..",default-features=false}
[lib]
path="src.rs"
[workspace]
members=["."]

[[bin]]
name="vertex"
path="fuzz_targets/vertex.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_into"
path="fuzz_targets/vertex_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="triangles"
path="fuzz_targets/triangles.rs"
test=false
doc=false
bench=false

[[bin]]
name="triangles_into"
path="fuzz_targets/triangles_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence"
path="fuzz_targets/sequence.rs"
test=false
doc=false
bench=false

[[bin]]
name="sequence_into"
path="fuzz_targets/sequence_into.rs"
test=false
doc=false
bench=false

[[bin]]
name="oct"
path="fuzz_targets/oct.rs"
test=false
doc=false
bench=false

[[bin]]
name="quat"
path="fuzz_targets/quat.rs"
test=false
doc=false
bench=false

[[bin]]
name="exp"
path="fuzz_targets/exp.rs"
test=false
doc=false
bench=false

[[bin]]
name="vertex_version"
path="fuzz_targets/vertex_version.rs"
test=false
doc=false
bench=false

[[bin]]
name="index_version"
path="fuzz_targets/index_version.rs"
test=false
doc=false
bench=false

[[bin]]
name="view"
path="fuzz_targets/view.rs"
test=false
doc=false
bench=false

[[bin]]
name="view_into"
path="fuzz_targets/view_into.rs"
test=false
doc=false
bench=false
